<?php
class SubCategoriasTableSeeder extends Seeder 
{
    public function run() 
    {
        $subCategorias = [
            "Antihelmínticos" => "1",
            "Antiprotozoarios (antiamibianos y antigiardiásicos)" => "1",
            "Antimaláricos" => "1",
            "Antitoxoplasma" => "1",
            "Antitripanosomas" => "1",
            "Antileishmaniásicos" => "1",
            "Indicaciones Varias" => "2",
            "Aminoglucósidos" => "2",
            "Betalactámicos" => "2",
            "Betaláctamicos con inhibidores de betalactamasas" => "2",
            "Betalactámicos carbapenémicos" => "2",
            "Fenicoles" => "2",
            "Lincosamidas" => "2",
            "Macrólidos" => "2",
            "Quinolonas" => "2",
            "Sulfonamidas" => "2",
            "Tetraciclinas" => "2",
            "Glucopéptidos" => "2",
            "Indicaciones Varias" => "3",
            "Indicaciones Varias" => "4",
            "Antiherpéticos" => "5",
            "Inhibidores nucleósidos de la transcriptasa reversa" => "5",
            "Inhibidores no Nucleósidos de la Transcriptasa reversa" => "5",
            "Inhibidores de la proteasa" => "5",
            "Indicaciones Varias" => "6",
            "Indicaciones Varias" => "7",
            "Bloqueadores de beta - adrenoreceptores" => "7",
            "Simpaticolíticos de acción central" => "7",
            "Vasodilatadores" => "7",
            "Bloqueadores de canales de calcio" => "7",
            "Inhibidores de enzima convertidora de angiotensina" => "7",
            "Antagonistas de receptores de angiotensina II" => "7",
            "Nitratos y nitritos" => "7",
            "Digitálicos" => "7",
            "Simpaticomiméticos" => "7",
            "Antiarrítmicos" => "7",
            "Adrenérgicos" => "7",
            "Indicaciones Varias" => "8",
            "Fibrinolíticos" => "9",
            "Heparina de bajo peso molecular" => "9",
            "Heparina no fraccionada" => "9",
            "Anticoagulantes Orales" => "9",
            "Antiagregantes plaquetarios" => "9",
            "Antídotos" => "9",           
            "Analgésicos, antiinflamatorios no esteroideos" => "10",
            "Antirreumáticos modificadores de la enfermedad" => "10",   
            "Indicaciones Varias" => "11",
            "Indicaciones Varias" => "12",
            "Indicaciones Varias" => "13",
            "Indicaciones Varias" => "14",
            "Indicaciones Varias" => "15",
            "Indicaciones Varias" => "16",
            "Bloqueadores neuromusculares" => "16",
            "Indicaciones Varias" => "17",
            "Indicaciones Varias" => "18",
            "Xantinas" => "19",
            "Anticolinérgicos" => "19",
            "Estimulantes beta 2 adrenérgicos" => "19",
            "Corticosteroides" => "19",
            "Indicaciones Varias" => "20",
            "Antieméticos" => "21",
            "Antagonistas de los receptores de la 5HT3" => "21",
            "Antiácidos" => "21",
            "Bloqueadores de receptores H2" => "21",
            "Inhibidores de la bomba de protones" => "21",
            "Laxantes" => "21",
            "Antihemorroidales" => "21",
            "Uso en tratamiento de díarreas" => "21",
            "Uso en afecciones hepáticas" => "21",
            "Indicaciones Varias" => "22",
            "Moduladores del afecto" => "22",
            "Antiparkinsonianos" => "22",
            "Anticonvulsivos" => "22",
            "Benzodiazepinas" => "22",
            "Antagonistas de benzodiazepinas" => "22",
            "Antidepresivos tricíclicos" => "22",
            "Inhibidores selectivos de la recaptación de serotonina" => "22",
            "Antipsicóticos atípicos" => "22",
            "Antisicóticos" => "22",
            "Antimigrañosos" => "22",
            "Medicamentos de uso en la demencia" => "22",
            "Uso en diabetes mellitus" => "23",
            "Hormonas hipotalámicas, pituitarias y otros agentes" => "23",
            "Hormonas tiroideas y agentes antitiroideos" => "23",
            "Hormonas suprarrenales, andrógenos y anabólicos" => "23",
            "Indicaciones Varias" => "24",
            "Inhibidores de la 3-hidroxi-3-metilglutaril CoA reductasa" => "25",
            "Fibratos" => "25",
            "Indicaciones Varias" => "26",
            "Agentes Alquilantes" => "26",
            "Antimetabolitos" => "26",
            "Antibióticos antitumorales y compuestos relacionados" => "26",
            "Protectores de toxicidad" => "26",
            "Fármacos que actúan en microtúbulos" => "26",
            "Inhibidores de la DNA topo - isomerasa" => "26",
            "Hormonas y enzimas" => "26",
            "Inmunomoduladores" => "26",
            "Inhibidores de la angiogénesis" => "26",
            "Vitaminas" => "27",
            "Sales de calcio y bifosfanatos" => "27",
            "Minerales" => "27",
            "Vitaminas y Minerales" => "27",
            "Hematínicos" => "27",
            "Indicaciones Varias" => "28",
            "Indicaciones Varias" => "29",
            "Indicaciones Varias" => "30",
            "Indicaciones Varias" => "31",
            "Indicaciones Varias" => "32",
            "Indicaciones Varias" => "33",
            "Indicaciones Varias" => "34",
            "Indicaciones Varias" => "35"
        ];
        

        foreach($subCategorias as $subcategoria => $idcategoria) {
            SubCategoria::create(array(
                "nombre" => $subcategoria,
                "categoria_id" => $idcategoria
            ));            
        }
    }
}